# Generated by Django 2.1.5 on 2019-02-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_recomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
