# Generated by Django 2.1.5 on 2019-02-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20190222_0343'),
        ('record', '0006_auto_20190221_1537'),
    ]

    operations = [
    ]
